quarkus.http.port=8082

quarkus.datasource.north.db-kind=postgresql
quarkus.datasource.north.username=north_app
quarkus.datasource.north.password=north_app_pw
quarkus.datasource.north.jdbc.url=jdbc:postgresql://localhost:55432/north

quarkus.datasource.south.db-kind=postgresql
quarkus.datasource.south.username=south_app
quarkus.datasource.south.password=south_app_pw
quarkus.datasource.south.jdbc.url=jdbc:postgresql://localhost:55433/south
