quarkus.http.port=8083

quarkus.datasource.north.db-kind=postgresql
quarkus.datasource.north.username=north_app
quarkus.datasource.north.password=north_app_pw
quarkus.datasource.north.jdbc.url=jdbc:postgresql://localhost:55432/north

quarkus.datasource.south.db-kind=postgresql
quarkus.datasource.south.username=south_app
quarkus.datasource.south.password=south_app_pw
quarkus.datasource.south.jdbc.url=jdbc:postgresql://localhost:55433/south

quarkus.datasource.east.db-kind=postgresql
quarkus.datasource.east.username=east_app
quarkus.datasource.east.password=east_app_pw
quarkus.datasource.east.jdbc.url=jdbc:postgresql://localhost:55434/east

quarkus.datasource.west.db-kind=postgresql
quarkus.datasource.west.username=west_app
quarkus.datasource.west.password=west_app_pw
quarkus.datasource.west.jdbc.url=jdbc:postgresql://localhost:55435/west
